# NuAWS Unified Completions Module  
# All AWS external completions consolidated
# Generated by Universal AWS Generator

# Completions are now pre-generated and located in completions/ directory
# Use the completions/mod.nu for loading all completions
export use ../completions/mod.nu *

# Individual completion exports (updated paths)
export use ../completions/s3.nu *
export use ../completions/ec2.nu *
export use ../completions/iam.nu *
export use ../completions/stepfunctions.nu *