# External completions for AWS S3API
# Generated by Universal AWS Generator

# Generic completions for s3api
export def "nu-complete aws s3api resources" []: nothing -> list<string> {
    try {
        # Generic resource completion - extend as needed
        []
    } catch {
        []
    }
}