# External completions for AWS STEPFUNCTIONS
# Generated by Universal AWS Generator

# Generic completions for stepfunctions
export def "nu-complete aws stepfunctions resources" []: nothing -> list<string> {
    try {
        # Generic resource completion - extend as needed
        []
    } catch {
        []
    }
}