# External completions for AWS IAM
# Generated by Universal AWS Generator

# IAM user completion
export def "nu-complete aws iam users" []: nothing -> list<string> {
    try {
        aws iam list-users | from json | get Users | get UserName
    } catch {
        []
    }
}

# IAM role completion
export def "nu-complete aws iam roles" []: nothing -> list<string> {
    try {
        aws iam list-roles | from json | get Roles | get RoleName
    } catch {
        []
    }
}