# NuAWS Unified Module Exports
# Generated by build.nu at 2025-10-08 11:07:49
# All AWS services pre-generated and ready for use

export use ec2.nu *
export use iam.nu *
export use s3.nu *
export use stepfunctions.nu *

# Service discovery function
export def "nuaws services" []: nothing -> list<string> {
    [ec2, iam, s3, stepfunctions]
}
