# Tests for AWS S3 Service Module
# Generated by Universal AWS Generator

use nutest

#[before-each]
def setup [] {
    $env.S3_MOCK_MODE = true
    { service: "s3" }
}

#[after-each]  
def cleanup [] {
    $env.S3_MOCK_MODE = false
}

