# External completions for AWS LAMBDA
# Generated by Universal AWS Generator

# Lambda function completion
export def "nu-complete aws lambda functions" []: nothing -> list<string> {
    try {
        aws lambda list-functions | from json | get Functions | get FunctionName
    } catch {
        []
    }
}